language: python
python:
    - "3.5"
    - "3.6"
branches:
  only:
    - master
install:
    - pip install .[test]
    - pip install codecov
    # Temporary cellmlmanip install, until it can be done with pip
    - pip install -e git://github.com/ModellingWebLab/cellmlmanip.git#egg=cellmlmanip

script:
    - python -m flake8
    - python -m isort --verbose --check-only --diff --recursive chaste_codegen
    - python -m pytest -m "not all_models" --cov=chaste_codegen chaste_codegen
after_success:
    - codecov
