language: python
python:
    - "3.6"
install:
    - pip install .[test]
    - pip install codecov
script:
    - python -m flake8
    - python -m pytest --cov=fccodegen fccodegen
after_success:
    - codecov
