language: python
python:
    - "3.5"
    - "3.6"
branches:
  only:
    - master
install:
    - pip install .[test]
    - pip install codecov
    # Temporary cellmlmanip install, until it can be done with pip
    - pip install -e git://github.com/ModellingWebLab/cellmlmanip.git#egg=cellmlmanip

script:
    - python -m flake8
    - if [[ $TRAVIS_EVENT_TYPE == "cron" ]] ; then python -m pytest -m cronjob --cov=chaste_codegen chaste_codegen ; else python -m pytest -m "not cronjob and not all_models" --cov=chaste_codegen chaste_codegen ; fi
after_success:
    - codecov
