name: build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.10"
            sympy-version: "1.10"
          - python-version: "3.11"
            sympy-version: "1.11"
          - python-version: "3.12"
            sympy-version: "1.12"
          - python-version: "3.13"
            sympy-version: "1.13"
          - python-version: "3.14"
            sympy-version: "1.14"
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v7
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install flake8 pytest
        python3 -m pip install .[test]
        python3 -m pip install "sympy==${{ matrix.sympy-version }}"
    - name: Lint with flake8
      run: |
        python3 -m flake8
    - name: Test sorting with isort
      run: |
        python3 -m isort --verbose --check-only --diff chaste_codegen setup.py
    - name: Test with pytest
      run: |
        python3 -m pytest --cov --cov-config=.coveragerc
    - uses: codecov/codecov-action@v6
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
